# Generated by Django 4.1.3 on 2023-03-13 11:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CurriculumVita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "starting_date",
                    models.DateField(default=datetime.datetime(1970, 1, 1, 0, 0)),
                ),
                ("end_date", models.DateField(default="2023-03-13")),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("surname", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(default="profile.jpg", upload_to="profile_pics"),
                ),
                (
                    "curriculum_vita",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio_app.curriculumvita",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CurriculumVitaSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=255)),
                (
                    "starting_date",
                    models.DateField(default=datetime.datetime(1970, 1, 1, 0, 0)),
                ),
                ("end_date", models.DateField(default="2023-03-13")),
                ("content", models.TextField(max_length=255)),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio_app.curriculumvita",
                    ),
                ),
            ],
        ),
    ]
