# Generated by Django 4.1.3 on 2023-03-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curriculumvita",
            name="end_date",
            field=models.DateField(default="2023-03-14"),
        ),
        migrations.AlterField(
            model_name="curriculumvitasection",
            name="end_date",
            field=models.DateField(default="2023-03-14"),
        ),
    ]
