# Generated by Django 4.1.3 on 2023-03-20 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0003_profile_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="curriculumvitasection",
            name="origin",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="curriculum_vita",
        ),
        migrations.DeleteModel(
            name="CurriculumVita",
        ),
        migrations.DeleteModel(
            name="CurriculumVitaSection",
        ),
    ]
